# Generated by Django 4.2 on 2025-05-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
