# Generated by Django 4.2 on 2025-05-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='remarks',
            field=models.TextField(default='Remarks not available'),
        ),
    ]
