# Generated by Django 4.2 on 2025-05-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teacher_detail_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='interested_categories',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='intrested_categories',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
