# Generated by Django 4.2 on 2025-05-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_studentcourseenrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseenrollment',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentcourseenrollment',
            old_name='Student',
            new_name='student',
        ),
    ]
