# Generated by Django 4.2 on 2025-05-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserating',
            name='rating',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
