# Generated by Django 4.2 on 2025-05-18 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_courserating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '4. Students'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '5. Enrolled Courses'},
        ),
        migrations.DeleteModel(
            name='CourseRating',
        ),
    ]
