# Generated by Django 4.2 on 2025-05-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_studentcourseenrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Course Rating'},
        ),
        migrations.AlterModelOptions(
            name='studentfavoritecourses',
            options={'verbose_name_plural': '8. Student Favorite Courses'},
        ),
    ]
